[package]
name = "andromeda-deploy"
version = "0.0.1"
edition = "2021"
rust-version = "1.75.0"
description = "The deploy tool for aOS"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3", "cosmwasm_1_2"] }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = "0.8.10"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
semver = { workspace = true }
cw20 = { version = "1.0.1" }
cw20-base = { workspace = true, features = ["library"] }
cw721-base = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw-asset = { version = "3.0.0" }
thiserror = { version = "1.0.21" }
lazy_static = "1"
hex = "0.4"
regex = { version = "1.9.1", default-features = false }
andromeda-macros = { workspace = true }
strum_macros = { workspace = true }
cw721 = { workspace = true }
serde-json-wasm = "0.5.0"
enum-repr = { workspace = true }
sha2 = "0.10.8"
cw-orch = { workspace = true }
cw-orch-daemon = "0.24.2"
andromeda-kernel = { version = "1.1.1", path = "../../contracts/os/andromeda-kernel", features = [
    "testing",
] }
andromeda-adodb = { version = "1.1.1", path = "../../contracts/os/andromeda-adodb", features = [
    "testing",
] }
andromeda-vfs = { version = "1.1.1", path = "../../contracts/os/andromeda-vfs", features = [
    "testing",
] }
andromeda-economics = { version = "1.1.1", path = "../../contracts/os/andromeda-economics", features = [
    "testing",
] }
andromeda-ibc-registry = { version = "1.0.1", path = "../../contracts/os/andromeda-ibc-registry", features = [
    "testing",
] }
andromeda-splitter = { path = "../../contracts/finance/andromeda-splitter", features = [
    "testing",
] }
andromeda-validator-staking = { path = "../../contracts/finance/andromeda-validator-staking", features = [
    "testing",
] }
andromeda-std = { workspace = true }
env_logger = "0.11.5" # or whatever the latest version is
log = "0.4" # env_logger depends on the log crate
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
chrono = "0.4"

[dev-dependencies]
cw-multi-test = { version = "1.0.0" }
