[package]
name = "andromeda-testing"
version = "0.1.0"
authors = ["Connor Barr <crnbarr@gmail.com>"]
edition = "2018"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cw721 = "0.9.1"
cw20 = { version = "0.9.1" }
terra-cosmwasm = { version = "2.2.0" }

common = { path = "../common", version = "0.1.0" }
andromeda-non-fungible-tokens = { version = "0.1.0", path = "../andromeda-non-fungible-tokens" }
andromeda-app = { version = "0.1.0", path = "../andromeda-app" }
andromeda-modules = { version = "0.1.0", path = "../andromeda-modules" }
