[package]
name = "andromeda-testing"
version = "1.0.0"
authors = ["Connor Barr <crnbarr@gmail.com>"]
edition = "2018"
description = "Testing utilities for Andromeda Digital Object Contracts"
license = "MIT"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw721 = { workspace = true }
cw20 = { workspace = true }
prost = "0.9.0"
anyhow = "1.0.79"

andromeda-non-fungible-tokens = { workspace = true }
andromeda-app = { version = "1.0.1", path = "../andromeda-app" }
andromeda-modules = { version = "1.0.0", path = "../andromeda-modules" }
andromeda-adodb = { version = "1.0.0", path = "../../contracts/os/andromeda-adodb", features = [
    "testing",
] }
andromeda-kernel = { version = "1.0.0", path = "../../contracts/os/andromeda-kernel", features = [
    "testing",
] }
andromeda-vfs = { version = "1.0.0", path = "../../contracts/os/andromeda-vfs", features = [
    "testing",
] }
andromeda-economics = { version = "1.0.0", path = "../../contracts/os/andromeda-economics", features = [
    "testing",
    "library",
] }
andromeda-std = { workspace = true }
serde = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { workspace = true }
anyhow = "1.0.79"
