[package]
name = "andromeda-finance"
version = "1.0.0"
edition = "2021"
rust-version = "1.75.0"
description = "Utility methods and message definitions for the Andromeda Finance Contracts"
license = "MIT"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]
testing = ["cw-multi-test"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["staking"] }
cosmwasm-schema = { workspace = true }
serde = { version = "1.0.216", default-features = false, features = ["derive"] }
cw-utils = { workspace = true }
cw721 = { workspace = true }
cw721-base = { workspace = true }
cw20 = { workspace = true }
schemars = { version = "0.8.10" }

andromeda-std = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-orch = { workspace = true }
cw-multi-test = { workspace = true, optional = true }
