version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "ci: skip-changelog"
    ignore:
      - dependency-name: "cosmwasm-std"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "chrono"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "ci: skip-changelog"
