[package]
name = "ado-base"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
withdraw = ["cw-asset", "cw20"]
modules = []
instantiate = ["primitive"]
primitive = []

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cw-storage-plus = "0.9.1"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
common = { version = "0.1.0", path = "../../packages/common" }

cw20 = { version = "0.9.1", optional = true}
cw-asset = { version = "1.0.2", optional = true }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
terra-cosmwasm = { version = "2.2.0" }
cw20 = { version = "0.9.1" }
