[package]
name = "andromeda-std"
version = "1.5.0"
edition = "2021"
rust-version = "1.75.0"
description = "The standard library for creating an Andromeda Digital Object"
license = "MIT"

[features]
primitive = []
instantiate = []
rates = ["andromeda-macros/rates"]
deploy = []
distribution = ["prost", "osmosis-std-derive"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3", "cosmwasm_1_2"] }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = "0.8.10"
serde = { version = "1.0.215", default-features = false, features = ["derive"] }
semver = { workspace = true }
cw20 = { version = "1.0.1" }
cw20-base = { workspace = true, features = ["library"] }
cw721-base = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw3 = { workspace = true }
cw-asset = { version = "3.0.0" }
thiserror = { version = "2.0.3" }
lazy_static = "1"
hex = "0.4"
regex = { version = "1.9.1", default-features = false }
andromeda-macros = { workspace = true }
strum_macros = { workspace = true }
cw721 = { workspace = true }
serde-json-wasm = "1.0.1"
enum-repr = { workspace = true }
sha2 = "0.10.8"
osmosis-std-derive = { version = "0.15.3", optional = true }
prost = { version = "0.11.2", default-features = false, features = [
    "prost-derive",
], optional = true }

[dev-dependencies]
cw-multi-test = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-orch = { workspace = true }
