[package]
name = "andromeda-non-fungible-tokens"
version = "1.0.0"
edition = "2021"
rust-version = "1.69.0"
description = "Message definitions and utility methods for Andromeda non-fungible token contracts"
license = "MIT"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
cw-utils = { workspace = true }
cw721 = { workspace = true }
cw721-base = { workspace = true }
cw20 = { workspace = true }

andromeda-std = { workspace = true }
