[package]
name = "andromeda-splitter"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "0.16.7" }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.3"
cw-storage-plus = "0.9.1"
cw2 = "0.9.1"

andromeda-protocol = { version = "0.1.0", path = "../../packages/andromeda_protocol" }
ado-base = { path = "../../packages/ado_base", version = "0.1.0", features = ["modules"] }
common = { version = "0.1.0", path = "../../packages/common" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
