[package]
name = "andromeda-protocol"
version = "0.1.0"
authors = ["Connor Barr <crnbarr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "0.16.0" }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.3"
cw721 = "0.9.1"
cw-storage-plus = "0.9.1"
protobuf = { version = "2", features = ["with-bytes"] }
terra-cosmwasm = { version = "2.2.0" }