[package]
name = "andromeda-app"
version = "1.0.1"
edition = "2021"
rust-version = "1.65.0"
description = "Utility methods and message definitions for the Andromeda App Contract"
license = "MIT"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["cosmwasm_1_2"] }
cosmwasm-schema = { workspace = true }
serde = { workspace = true }
andromeda-std = { workspace = true }

[dev-dependencies]
cw-multi-test = { version = "1.0.0" }
