name: starship-getting-started
 
chains:
  - id: osmosis-1
    name: osmosis
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      grpc: 9091
      faucet: 8001
  - id: gaia-1
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      grpc: 9092
      faucet: 8002
 
relayers:
  - name: osmos-gaia
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - gaia-1
 
registry:
  enabled: true
  ports:
    rest: 8081