[package]
name = "andromeda-ecosystem"
version = "0.1.0"
edition = "2018"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.1.6"
cosmwasm-schema = "1.1.6"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.10"
#mirror-protocol = "2.1.1"
#astroport = "1.0.1"
cw20 = "0.16.0"
#cosmwasm-bignumber = "2.2.0"
cw-storage-plus = "0.16.0"

common = { path = "../common", version = "0.1.0" }
cw-asset = { version = "2.0.0" }
