name: Build Contracts & Schemas

on:
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Contracts
    if: >
      !contains(github.event.pull_request.labels.*.name, 'ci: skip-build') && (
        (github.base_ref == 'development' || 
          github.base_ref == 'main' || 
          contains(github.event.pull_request.labels.*.name, 'ci: build')) 
      )
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
      - run: rustup override set 1.75.0
      - run: rustup target add wasm32-unknown-unknown
      - uses: actions/checkout@v4
      - name: Install Binaryen
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/install_binaryen.sh"
          "${GITHUB_WORKSPACE}/scripts/install_binaryen.sh"
      - name: Build
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/build_all.sh"
          make build
          sudo make version-map
      - name: Check contract sizes
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/file-size.sh"
          "${GITHUB_WORKSPACE}/.github/file-size.sh"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts
          path: ./artifacts/
          if-no-files-found: error

  build-schemas:
    runs-on: ubuntu-latest
    name: Schemas
    if: >
      !contains(github.event.pull_request.labels.*.name, 'ci: skip-build') && (
        (github.base_ref == 'development' || 
          github.base_ref == 'main' || 
          contains(github.event.pull_request.labels.*.name, 'ci: build')) 
      )
    steps:
      - uses: actions/checkout@v4
      - name: Build Schema
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/build_schema.sh"
          make schemas
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: schema
          path: ./schemas/
          if-no-files-found: error
