name: Bump Changed Crates

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Detect Changed Crates
        run: |
          chmod +x scripts/detect_changed_crates.sh
          CHANGED_CRATES=$(./scripts/detect_changed_crates.sh)
          echo "Changed crates: $CHANGED_CRATES"
          echo "changed_crates=$CHANGED_CRATES" >> $GITHUB_ENV

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Release Changed Crates with Pre-release Tags
        run: |
          for crate in ${{ env.changed_crates }}; do
            echo "Releasing $crate with pre-release tag 'b'"
            cd $crate
            cargo release pre --pre-release b --no-publish
            cd -
          done
