name: Deploy OS

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network to deploy to"
        required: true
        type: string
      kernel_address:
        description: "Kernel address"
        required: false
        type: string

jobs:
  build_contracts:
    if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic"]', github.actor)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Contracts
        run: |
          make build
          make version-map
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: ./artifacts/
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_CHAIN: ${{ inputs.network }}
      DEPLOYMENT_KERNEL_ADDRESS: ${{ inputs.kernel_address }}
      SLACK_WEBHOOK_URL: "${{ secrets.DEPLOY_SLACK_WEBHOOK_URL }}"
      TEST_MNEMONIC: "${{ secrets.DEPLOY_TEST_MNEMONIC }}"
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
      - name: Download Contracts
        uses: actions/download-artifact@v2
        with:
          name: contracts
          path: "./artifacts"
      - name: Deploy
        run: cargo run -p andromeda-deploy
