name: Deploy OS

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network to deploy to"
        required: true
        type: string
      kernel_address:
        description: "Kernel address"
        required: false
        type: string

jobs:
  #   build_contracts:
  #     if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic"]', github.actor)
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v4
  #       - run: make build
  #       - run: make version-map
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_CHAIN: ${{ inputs.network }}
      DEPLOYMENT_KERNEL_ADDRESS: ${{ inputs.kernel_address }}
      SLACK_WEBHOOK_URL: "${{ secrets.DEPLOY_SLACK_WEBHOOK_URL }}"
      TEST_MNEMONIC: "${{ secrets.DEPLOY_TEST_MNEMONIC }}"
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          components: rustfmt, clippy
          profile: minimal
          override: true
      - run: cargo run -p andromeda-deploy
