name: Rust

on:
  push:
    paths: ["**.*"]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - run: cargo fetch --verbose
      - run: cargo clippy --version
      - run: cargo clippy --all --all-targets -- -D warnings
      - run: cargo fmt -- --check

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose --workspace

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          required-permission: write
      - name: Build Schema
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build_schema.sh"
          "${GITHUB_WORKSPACE}/build_schema.sh"
      - name: Build
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build.sh"
          "${GITHUB_WORKSPACE}/build.sh"
      - name: Check contract sizes
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/file-size.sh"
          "${GITHUB_WORKSPACE}/.github/file-size.sh"
