name: Rust

on:
  push:
    paths: ["**.*"]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test & Build
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build.sh"
          "${GITHUB_WORKSPACE}/build.sh"
          cargo test --verbose --workspace
      - name: Check contract sizes
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/file-size.sh"
          "${GITHUB_WORKSPACE}/.github/file-size.sh"
