name: Formatting Check & Test

on:
  push:
    paths: ["**.*"]
  pull_request:
    branches: [main, development]

env:
  CARGO_TERM_COLOR: always

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
          components: rustfmt, clippy
          override: true
      - run: cargo fetch --quiet
      - name: Run linting checks
        run: |
          cargo clippy --quiet --all --all-targets -- -D warnings &
          cargo fmt -- --check &
          wait

  contract-tests:
    name: Contract Tests
    needs: linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        test-type: ["integration-test", "unit-test"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
      - run: make ${{ matrix.test-type }}
